/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ProjectsIdFinishingRouteImport } from './routes/projects.$id.finishing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdFinishingRoute = ProjectsIdFinishingRouteImport.update({
  id: '/finishing',
  path: '/finishing',
  getParentRoute: () => ProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/$id/finishing': typeof ProjectsIdFinishingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/$id/finishing': typeof ProjectsIdFinishingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/$id/finishing': typeof ProjectsIdFinishingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/$id' | '/projects/$id/finishing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/$id' | '/projects/$id/finishing'
  id: '__root__' | '/' | '/projects/$id' | '/projects/$id/finishing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/finishing': {
      id: '/projects/$id/finishing'
      path: '/finishing'
      fullPath: '/projects/$id/finishing'
      preLoaderRoute: typeof ProjectsIdFinishingRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface ProjectsIdRouteChildren {
  ProjectsIdFinishingRoute: typeof ProjectsIdFinishingRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdFinishingRoute: ProjectsIdFinishingRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
